<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Analyse_Recursive_CS</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Analyse_Recursive.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Analyse_Recursive.ico" />
  </ItemGroup>

</Project>